### ISSUE TITLE
OFX Version

### ISSUE THREAD

**Issue by tkiener** [thehackerati/THVideoFaceSwapper#11]
Hi there,
great project so far. I just wonder which openframeworks version this project is compatible with.
Can I use 0.92 or stick to 0.84?

Thanks a lot.
Best,
Tim

**Comment by evfemist** [comment]
I was able to run it on 0.92

**Comment by cjrieck** [comment]
Currently the project is updated to run on v0.9.2. Let me know if you have any more problems!
