### ISSUE TITLE
[ error ] ofAppiOSWindow instantiated more than once

### ISSUE THREAD

**Issue by MenLonII** [thehackerati/THVideoFaceSwapper#12]
Xcode prints this error

**Comment by ghost** [comment]
Same issue too:

[ error ] ofAppiOSWindow instantiated more than once
(lldb)

**Comment by hazkiel** [comment]
any luck fixing the issue?

**Comment by emile818** [comment]
check this out https://github.com/openframeworks/openFrameworks/pull/4344

**Comment by emile818** [comment]
go to src/main.mm and comment out ofSetupOpenGL.

Or Replace your main.mm by the own below and it will fix this issue
https://gist.github.com/emile818/241acf8846a6a235a044

**Comment by miteshpotenza** [comment]
error: /Users/libs/openFrameworksCompiled/project/ios/CoreOF.xcconfig: No such file or directory
Also in addons there are no such files available.
Please help me

**Comment by miteshpotenza** [comment]
error: /Users/libs/openFrameworksCompiled/project/ios/CoreOF.xcconfig: No such file or directory
or also no such files available in addons.
Please help me to solve this

**Comment by cjrieck** [comment]
Hey everyone! Let me know if the issue still persists after using @emile818's solution. Closing for now
