### ISSUE TITLE
#include "ofMain.h" not found

### ISSUE THREAD

**Issue by syrakozz** [thehackerati/THVideoFaceSwapper#13]
i download the project once i opend i get 
 "ofMain.h" not found

**Comment by MenLonII** [comment]
@syrakozz  you should pull the project to the MyApps of openframeworks(http://openframeworks.cc/download/)

**Comment by MiteshiOS** [comment]
@MenLonII  i have already project in MyApps of openframeworks but still i got ofMain.h file not found

**Comment by cjrieck** [comment]
Seems like this issue is solved. Closing for now
