### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by arturoc** [thehackerati/THVideoFaceSwapper#14]
Hi 

This project seems to be a copy almost line by line of https://github.com/arturoc/FaceSubstitution which is copyrighted to Arturo Castro and Kyle McDonald and open sourced under an MIT license. Because of that you should have a copy of this file: https://github.com/arturoc/FaceSubstitution/blob/master/license.md in this repo. i might have missed it but i can't find it. can you please add it? 

thanks

**Comment by cjrieck** [comment]
Hey @arturoc! I'm very sorry about the lack of licensing in the repo. I just added the license per your request and it can be found in the root of the project on `master` now :) also, thank you for your awesome work!
