### ISSUE TITLE
Files not found

### ISSUE THREAD

**Issue by MiteshiOS** [thehackerati/THVideoFaceSwapper#18]
![screen shot 2016-05-26 at 5 47 49 pm](https://cloud.githubusercontent.com/assets/17427703/15574877/76e3deda-236d-11e6-9164-a6a49b254dd2.png)

Please help me to solve this

**Comment by elekezem** [comment]
same error happen to me of_9.3_ios

**Comment by elekezem** [comment]
soleved this error by making c++ flag.

**Comment by MiteshiOS** [comment]
Yes but where i have to make this flag. Please can you show some steps. In latest version of openFrameworks v0.9.3 if i click on unorderd_map file there is no such file. But i have another version of openFramework from GitHub in which i have unorderd_map file. please help me to clear this things.
The versions i have
[https://github.com/openframeworks/openFrameworks](url)
[http://openframeworks.cc/download/](url)

**Comment by MiteshiOS** [comment]
@elekezem  i solved above issues buy making "config +=c++11" flag in project.xcconfig but now ofMain.h file not found occurs. please help me

**Comment by cjrieck** [comment]
Currently the app is built for version 0.9.2 of openFrameworks. I will take a look into support for v0.9.3

**Comment by cjrieck** [comment]
I have built the app for v0.9.3 and updated the `main.mm` file with new window settings. Let me know if the problem still persists with this new version. Closing for now
