### ISSUE TITLE
error: /Users/libs/openFrameworksCompiled/project/ios/CoreOF.xcconfig: No such file or directory

### ISSUE THREAD

**Issue by youxigit** [thehackerati/THVideoFaceSwapper#19]

**Comment by MiteshiOS** [comment]
You need to place the project in openFrameworks. 
1. First download OpenFrameWorks [https://github.com/openframeworks/openFrameworks](url) or latest version [http://openframeworks.cc/download/](url)
2.After that place your project in  ~/openFrameworks/apps/myApps/ 
3. And after that open project.

**Comment by cjrieck** [comment]
Thanks @MiteshiOS! I will close this issue for now. Feel free to reopen if there are further issues
