### ISSUE TITLE
ofxCvImage.h have list of erros

### ISSUE THREAD

**Issue by MiteshiOS** [thehackerati/THVideoFaceSwapper#21]
![screen shot 2016-06-02 at 12 36 19 pm](https://cloud.githubusercontent.com/assets/17427703/15736670/e4cf7282-28be-11e6-90ba-813acb6c7f30.png)

Please help me to solve this.

**Comment by cjrieck** [comment]
Hey @MiteshiOS! I'm sorry you're experiencing problems. May I ask what version of openFrameworks you're using?

**Comment by cjrieck** [comment]
Also, I recommend trying the solution I posted in issue #20

**Comment by MiteshiOS** [comment]
Hey @cjrieck  i have already latest version of openFrameworks v0.9.3 from official site of openFrameWorks and i also apply your solution.
First of all i removed ofxCv and ofxFaceTracker  from addons folder and again i add lib and src folder in both which is downloaded from GitHub. But it gives me "ofxCv/ContourFinder.h" file not found , so i also manually did #include "ContourFinder.h" instead of #include "ofxCv/ContourFinder.h" for all the related files of ofxCv and ofxFaceTracker. But after that there are many error i attach screen shot of that please review it and give me suggestion. 
![screen shot 2016-06-08 at 2 38 10 pm](https://cloud.githubusercontent.com/assets/17427703/15903125/bc63e8a0-2dc8-11e6-82b4-70b4e4dcf9b8.png)

**Comment by cjrieck** [comment]
@MiteshiOS are you only adding the `lib` and `src` directories to the `myApps` directory? This is what my file system looks like and everything works fine

![screen shot 2016-06-09 at 10 13 28 am](https://cloud.githubusercontent.com/assets/1785533/15932748/d50cfb96-2e2a-11e6-83f1-a7c195eb98ce.png)

**Comment by cjrieck** [comment]
Hey @MiteshiOS. Did you have a chance to try my suggestion out?

**Comment by MiteshiOS** [comment]
@cjrieck Yes now it's perfect run. Thank you.

**Comment by cjrieck** [comment]
Awesome! Glad it all worked!
